/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;




import Logica.*;

import java.io.BufferedWriter;
import java.io.File;

import java.io.FileWriter;
import java.io.IOException;

import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class frm_listado_Entes extends javax.swing.JFrame {

    /**
     * Creates new form frm_listado_Entes
     */
    conexcion con = new conexcion();
    Entes en = new Entes();
    String ruta;

    public frm_listado_Entes() {

        initComponents();
        BufferedWriter bw = null;
        FileWriter fw = null;
        File repo = new File("C:\\Diseño Reporte");
        File dise = new File("C:\\Reportes");
        File inicio_1 = new File("diseño\\logo.png");
        File inicio_2 = new File("diseño\\MINECO-02.jpg");
        File inicio_3 = new File("diseño\\rem.jasper");
        File fin_1 = new File("C:\\Diseño Reporte\\logo.png");
        File fin_2 = new File("C:\\Diseño Reporte\\MINECO-02.jpg");
        File fin_3 = new File("C:\\Diseño Reporte\\rem.jasper");

        ruta = dise.toString();
        funciones fun = new funciones();

        if (repo.exists() && dise.exists()) {

        } else {
            repo.mkdir();
            dise.mkdir();
            try {
                fun.copyFile(inicio_1, fin_1);
                fun.copyFile(inicio_2, fin_2);
                fun.copyFile(inicio_3, fin_3);
            } catch (IOException ex) {

            }

        }
        //this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        //tbl_entes.setEnabled(false);
        txt_cod_ente.setVisible(false);
        txt_cod_ente.setEditable(false);
        txt_id.setEditable(false);
        txt_nombre.setEditable(false);
        String[] dato = new String[8];

        Statement st;
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("CODIGO");
        tbl.addColumn("NOMBRE ENTE");
        tbl.addColumn("RAZON SOCIAL");
        tbl.addColumn("NIT_ENTE");
        tbl.addColumn("DIRECCION FISCAL");
        tbl.addColumn("TELEFONO");
        tbl.addColumn("TELEFONO ALTERNO");
        tbl.addColumn("EMAIL");
        tbl_entes.setModel(tbl);
        try {
            st = con.getConnection().createStatement();
            ResultSet result = st.executeQuery(en.ente());
            while (result.next()) {
                dato[0] = result.getString(1);
                dato[1] = result.getString(2);
                dato[2] = result.getString(3);
                dato[3] = result.getString(4);
                dato[4] = result.getString(5);
                dato[5] = result.getString(6);
                dato[6] = result.getString(7);
                dato[7] = result.getString(8);
                tbl.addRow(dato);

            }
            //con.desconectar();

        } catch (Exception ex) {
            System.err.println(ex);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cod_ente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(133, 0, 161));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_entes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_entes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_entesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_entes);

        jButton1.setText("CERTIFICADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NIT DEL ENTE");

        jLabel2.setText("NOMBRE DEL ENTE");

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 146, 231));
        jLabel4.setText("CREACION DE CERTIFICADO");

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cod_ente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(50, 50, 50)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(50, 50, 50)))
                                .addGap(797, 797, 797))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(791, 791, 791))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(408, 408, 408)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(398, 398, 398))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(657, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(615, 615, 615))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(txt_cod_ente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButton2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (txt_id.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN ENTE ANTES");
            } else {
                long nit_ente = Long.parseLong(txt_id.getText());
                int cod_ente = Integer.parseInt(txt_cod_ente.getText().toString());
                String[] opciones = {"NUEVO CORRELATIVO", "MISMO CORRELATIVO"};

                funciones fun = new funciones();

                String nombre_ente = txt_nombre.getText().toString(),
                        nit = txt_id.getText().toString(),
                        cod_certifica = "", envio = "", cod_certifica_viejo = "", clave = "";

                int pres_nue = JOptionPane.showConfirmDialog(null, "DESEA REALIZAR UN NUEVO CERTIFICADO", "CONFIRMAR CERTIFICADO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (txt_nombre.getText().toString().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "debe seleccionar un ente primero");

                } else {
                    if (pres_nue == 0) {
                        cod_certifica_viejo = fun.nit_ente(txt_id.getText());
                        if (cod_certifica_viejo.equals("")) {
                            cod_certifica = fun.procedimiento(envio);

                            crea_certifica(cod_certifica, envio, cod_ente, nombre_ente, nit_ente, nit, true);
                        } else {
                            //int press_nuevo_cert = JOptionPane.showConfirmDialog(null, "EL ENTE POSEE UN CERTIFICADO YA CREADO CON EL CORRELATIVO: " + cod_certifica_viejo + "\n" + "¿Desea crear un nuevo certificado?", "CONFIRMAR CERTIFICADO",JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
                            int press_nuevo_cert = JOptionPane.showOptionDialog(null, "EL ENTE POSEE UN CERTIFICADO YA CREADO CON EL CORRELATIVO: " + cod_certifica_viejo + "\n" + "¿Que desea hacer?",
                                    "CORRELATIVO",
                                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

                            if (press_nuevo_cert == 0) {
                                cod_certifica = fun.procedimiento(envio);
                                fun.cambio_estado(nit);
                                crea_certifica(cod_certifica, envio, cod_ente, nombre_ente, nit_ente, nit, true);
                            }
                            if (press_nuevo_cert == 1) {
                                JTextField txt = new JTextField();
                                txt.setText(fun.clave(txt_id.getText()));
                                JOptionPane.showMessageDialog(null, txt);
                                crea_certifica(cod_certifica_viejo, envio, cod_ente, nombre_ente, nit_ente, nit, false);

                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "SELECCIONE AL ENTE QUE DESEA MODIFICAR");
                    }
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void crea_certifica(String cod_certifica, String envio, int cod_ente, String nombre_ente, long nit_ente, String nit, boolean bandera) throws Exception {
        funciones fun = new funciones();
        String rut=ruta;
        if (bandera == true) {
            fun.inserta(cod_certifica, cod_ente, nombre_ente, nit_ente);//INSERTA CERTIFICADO
            fun.pdf_certi(nit, cod_certifica, ruta);
        }
        if (bandera == false) {
             fun.pdf_certi(nit, cod_certifica, ruta);
            
        }
    }

    

    private void tbl_entesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_entesMouseClicked
        int seleccion = tbl_entes.rowAtPoint(evt.getPoint());
        txt_id.setText(String.valueOf(tbl_entes.getValueAt(seleccion, 3)));
        txt_nombre.setText(String.valueOf(tbl_entes.getValueAt(seleccion, 1)));
        txt_cod_ente.setText(String.valueOf(tbl_entes.getValueAt(seleccion, 0)));
    }//GEN-LAST:event_tbl_entesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frm_principal ente = new frm_principal();
        ente.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listado_Entes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listado_Entes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listado_Entes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listado_Entes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listado_Entes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_entes;
    private javax.swing.JTextField txt_cod_ente;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
